# 工作目录
root = "."
tmp_dir = "tmp"

[build]
args_bin = ["-config", "configs/config.yaml"]
# 运行命令 windows ./tmp/main.exe linux darwin ./tmp/main
bin = "./tmp/main.exe"
# 构建命令
cmd = "go build -o ./tmp/main.exe ./cmd/server/main.go"
# 延迟时间
delay = 1000 # ms
# 忽略这些文件夹
exclude_dir = ["assets", "tmp", "vendor", "build", "deploy", "docs", ".idea", ".vscode", ".git", ".github", ".husky", ".codebuddy"]
# 排除以下文件的变化
exclude_file = []
exclude_regex = ["_test.go"]
# 监听以下文件的变化
include_dir = []
# 只需要监听go文件的变化
include_ext = ["go", "tpl", "tmpl", "html", "yaml", "yml"]
include_file = []
# 日志文件
log = "air.log"
# 清理生成的二进制文件
clean_on_exit = true
[log]
# 显示日志时间
time = true

[color]
# 自定义颜色
main = "magenta"
watcher = "cyan"
build = "yellow"
runner = "green"

[misc]
# 退出时删除tmp目录
clean_on_exit = true