version: '3.8'

services:
  # MySQL 8 服务
  mysql:
    image: mysql:8.0
    container_name: kunpeng-mysql-only
    restart: always
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
      - ../scripts/mysql:/docker-entrypoint-initdb.d
    environment:
      - MYSQL_ROOT_PASSWORD=kunpeng123
      - MYSQL_DATABASE=kunpeng
      - MYSQL_USER=kunpeng
      - MYSQL_PASSWORD=kunpeng123
      - TZ=Asia/Shanghai
    command: >
      --default-authentication-plugin=mysql_native_password
      --character-set-server=utf8mb4
      --collation-server=utf8mb4_unicode_ci
      --innodb-buffer-pool-size=256M
      --max-connections=200
    networks:
      - mysql-network

volumes:
  mysql-data:
    driver: local

networks:
  mysql-network:
    driver: bridge