app:
  name: "鲲鹏后台管理系统"
  mode: "development" # development, production, test
  version: "1.0.0"
  language: "zh-CN"
  trace_enable: true

server:
  host: "0.0.0.0"
  port: 8081
  read_timeout: 60s
  write_timeout: 60s

database:
  driver: "mysql"
  host: "127.0.0.1"
  port: 3306
  database: "kunpeng"
  username: "kunpeng"
  password: "kunpeng123"
  charset: "utf8mb4"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600
  show_sql: true

log:
  level: "debug" # debug, info, warn, error, dpanic, panic, fatal
  filename: "logs/kunpeng.log"
  max_size: 100    # 单个日志文件最大尺寸，单位MB
  max_backups: 10  # 最多保留多少个备份
  max_age: 30      # 文件最多保存多少天
  compress: true   # 是否压缩
  # SQL日志配置
  sql_filename: "logs/sql.log"
  sql_max_size: 50     # SQL日志文件最大尺寸，单位MB
  sql_max_backups: 5   # SQL日志最多保留多少个备份
  sql_max_age: 7       # SQL日志文件最多保存多少天
  sql_compress: true   # 是否压缩SQL日志

jwt:
  secret: "kunpeng_jwt_secret_key"
  issuer: "kunpeng"
  expire_time: 2h # 普通登录token有效期
  remember_me_expire_time: 720h # 记住我token有效期（30天）