# Kunpeng 应用程序配置文件

app:
  name: "kunpeng"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "localhost"
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "kunpeng"
  max_open_conns: 25
  max_idle_conns: 5
  conn_max_lifetime: 300s

logging:
  level: "info"
  format: "json"
  output: "stdout"
  file_path: "logs/app.log"
  max_size: 100
  max_backups: 3
  max_age: 28
  compress: true

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "kunpeng-jwt-secret-key-change-in-production"
  expire_time: 24h
  issuer: "kunpeng"