# 示例配置文件
# 复制此文件为 config.yaml 并根据实际环境修改配置

app:
  name: "kunpeng"
  version: "1.0.0"
  environment: "production"  # development/production
  debug: false

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "your_password_here"
  database: "kunpeng"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "your-jwt-secret-key-change-in-production"
  expire_time: 24h
  issuer: "kunpeng"

logging:
  level: "info"           # debug/info/warn/error
  format: "json"          # json/console
  output: "file"          # console/file/both
  file_path: "logs/app.log"
  max_size: 100           # MB
  max_backups: 7
  max_age: 30             # days
  compress: true
  # 分级别日志文件配置
  separate_files: false   # 是否启用分级别日志文件
  log_dir: "logs"         # 日志目录（启用分级别时使用）