# 分级别日志配置示例

app:
  name: "kunpeng"
  version: "1.0.0"
  environment: "development"
  debug: true

server:
  host: "0.0.0.0"
  port: 8080
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 60s

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "kunpeng"
  charset: "utf8mb4"
  parse_time: true
  loc: "Local"
  max_idle_conns: 10
  max_open_conns: 100
  conn_max_lifetime: 3600s

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 0
  pool_size: 10
  min_idle_conns: 5

jwt:
  secret: "test-jwt-secret-key"
  expire_time: 24h
  issuer: "kunpeng"

logging:
  level: "debug"          # debug/info/warn/error
  format: "json"          # json/console
  output: "both"          # console/file/both
  file_path: "logs/app.log"
  max_size: 10            # MB (小一点便于测试轮转)
  max_backups: 3
  max_age: 7              # days
  compress: true
  # 分级别日志文件配置
  separate_files: true    # 启用分级别日志文件
  log_dir: "logs"         # 日志目录