# 测试配置文件 - 用于演示配置热重载功能
app:
  name: "kunpeng-test"
  version: "1.0.1"
  environment: "test"
  debug: true

server:
  host: "0.0.0.0"
  port: 8081
  read_timeout: 30s
  write_timeout: 30s
  idle_timeout: 120s

database:
  driver: "mysql"
  host: "localhost"
  port: 3306
  username: "root"
  password: "password"
  database: "kunpeng_test"
  max_open_conns: 50
  max_idle_conns: 25
  conn_max_lifetime: 300s

redis:
  host: "localhost"
  port: 6379
  password: ""
  database: 1
  pool_size: 20
  min_idle_conns: 5

logging:
  level: "debug"
  format: "json"
  output: "file"
  file_path: "logs/test.log"
  max_size: 50
  max_backups: 10
  max_age: 30
  compress: true

jwt:
  secret: "test-secret-key-for-hot-reload"
  expire_time: 24h
  issuer: "kunpeng-test"